### ISSUE TITLE
生成图片被截断

### ISSUE THREAD

**Issue by TurbMZ** [tinyzh/drag-clip#1]
拖拽图片的容器使用了背景图片，当拖拽的图片放在容器最顶部时，可以合成完整的图片；但如果拖拽的图片放在容器非顶部，就会出现合成的图片被截断，只显示出拖拽图片放置位置的上下大约100-200px的图片信息，合成图片的总高度没错，但显示不全

**Comment by tinyzh** [comment]
不是很清楚你遇到了什么问题，下面是我之前遇到的几个问题，看能不能帮到你  https://www.jianshu.com/p/dd185085cf8d
